# Configuration from TopoStats run completed : 2024-10-21 18:53:18
# For more information on configuration and how to use it:
# https://afm-spm.github.io/TopoStats/main/configuration.html
base_dir: concat
cores: 2
disordered_tracing:
  mask_smoothing_params:
    dilation_iterations: 2
    gaussian_sigma: 2
    holearea_min_max: [0, null]
  min_skeleton_size: 10
  pad_width: 1
  pruning_params: {height_threshold: null, max_length: 10.0, method: topostats, method_outlier: mean_abs,
    method_values: mid}
  run: true
  skeletonisation_params: {height_bias: 0.6, method: topostats}
file_ext: .spm
filter:
  gaussian_mode: nearest
  gaussian_size: 1.0121397464510862
  otsu_threshold_multiplier: 1.0
  remove_scars: {max_scar_width: 4, min_scar_length: 16, removal_iterations: 2, run: false,
    threshold_high: 0.666, threshold_low: 0.25}
  row_alignment_quantile: 0.5
  run: true
  threshold_absolute: {above: 1.0, below: -1.0}
  threshold_method: std_dev
  threshold_std_dev: {above: 1.0, below: 10.0}
grains:
  absolute_area_threshold:
    above: [300, 3000]
    below: [null, null]
  direction: above
  otsu_threshold_multiplier: 1.0
  remove_edge_intersecting_grains: true
  run: true
  smallest_grain_size_nm2: 50
  threshold_absolute: {above: 1.0, below: -1.0}
  threshold_method: std_dev
  threshold_std_dev: {above: 1.0, below: 10.0}
  unet_config: {grain_crop_padding: 2, lower_norm_bound: -1.0, model_path: null, upper_norm_bound: 5.0}
grainstats: {cropped_size: -1, edge_detection_method: binary_erosion, extract_height_profile: true,
  run: true}
loading: {channel: Height}
log_level: info
nodestats: {branch_pairing_length: 20.0, node_extend_dist: 14.0, node_joining_length: 7.0,
  pad_width: 1, pair_odd_branches: false, run: true}
ordered_tracing: {ordering_method: nodestats, pad_width: 1, run: true}
output_dir: concat
plotting:
  axes: true
  cmap: null
  colorbar: true
  histogram_log_axis: false
  image_set: core
  mask_cmap: blue_purple_green
  num_ticks: [null, null]
  pixel_interpolation: null
  run: true
  savefig_dpi: 100
  savefig_format: null
  style: topostats.mplstyle
  zrange: [null, null]
splining: {method: rolling_window, rolling_window_size: 2e-08, run: true, spline_circular_smoothing: 5.0,
  spline_degree: 3, spline_linear_smoothing: 5.0, spline_step_size: 7e-09}
summary_stats: {config: null, run: true}
